### PR TITLE
Try to fix DDX Dalitz variation

### LINKED ISSUE #123: fix logic for setting minimum mDD for dalitz corrections
Currently committed `master` sets the wrong minimum for mDD. For the D0 sample it should be m_D+m_D (~1864.whatever *2), for the Dst sample it should be m_Dst+m_D (~2010+1864.whatever). The minimum is *not* set by parent, it is set by sample.

https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b150b044dc770f50f7bd6ff7ca8dac3696eb5a71/include/functor/rdx/cut.h#L311-L316

I had thought this was fixed as per an earlier discussion, and maybe it's just fixed in some local somewhere, but if not it needs to be fixed and the change needs to be propagated to the histograms.

### PR DESCRIPTION
**Pull request by yipengsun**
This should fix #123 

I change the following:

- We now can tell apart the muonic DDX from the tauonic DDX with `is_ddx_mu` flag
- For muonic DDX only, add the following global cut:
    - The `min(mDD)` is set to `1864*2` for `D0` chan, `2010 + 1864` for `D*` chan
    - The `max(mDD)` is set such that there is enough phase space to produce a `K`
- Simplify the Dalitz-weight calculation: no longer test the range of inputs

Here's `mDD` for `D0` chan
test_d0

`mDD` for `D*` chan
test_dst

@afernez @CoffeeIntoScience Please review my changes to see if they make sense.

### CODE REVIEW

**Comment by CoffeeIntoScience** [comment]
The `is_ddx_mu` seems to be actually checking if it is a 3-body decay rather than a two-body decay. Are you sure that the two-body muonic B->DD decays still go through to the template with the correct BF weights and all?

I admit this should be more obvious to me but I'm not used to parsing the YML setup

**Comment by CoffeeIntoScience** [comment]
> The is_ddx_mu seems to be actually checking if it is a 3-body decay rather than a two-body decay. Are you sure that the two-body muonic B->DD decays still go through to the template with the correct BF weights and all?

> I admit this should be more obvious to me but I'm not used to parsing the YML setup

The logical issue is that you're selecting out the DDX muonic, then requiring *ALL* pass a cut that will only be expected to be passed by DDK. There's still DD and DDs that are muonic and will not and should not pass this cut, but also should not receive dalitz weights. 

So in that light 
>For muonic DDX only, add the following global cut:
>    The min(mDD) is set to 1864*2 for D0 chan, 2010 + 1864 for D* chan
>    The max(mDD) is set such that there is enough phase space to produce a K

is at best dangerous logic for the template building stage if you aren't aware that this cut removes the two-body and you don't think to keep it.

**Comment by yipengsun** [comment]
Now I remove this global selection of **ONLY** selecting **muonic DDK** and removing D_s / two-body DD.

Instead, now I have a flag called `is_dal_variable` meaning the particular event is subject to Dalitz variation. If so, the event will receive a Dalitz weight from `WT_DALITZ`. Otherwise the event will have a weight of 1 (i.e. no Dalitz variation).

File: include/functor/rdx/truth_match.h [hunk 1]
```diff
@@ -28,6 +28,14 @@ bool IS_DDX(int decay_id) {
   return true;
 }
 
+bool IS_DDX_MU(int decay_id) {
+  auto ddx_ids = vector<int>{11894600, 12893600, 11894610, 12895400};
```
Comment (CoffeeIntoScience) [inline include/functor/rdx/truth_match.h:32]: @afernez please verify the IDs here, I don't have them in front of me. Otherwise fine

**Review by CoffeeIntoScience — APPROVED** [review]

**Comment by CoffeeIntoScience** [comment]
Looks good to me now. I only left a note that it would be good for @afernez to specifically check the MC IDs enumerated for your one flag since it would be much faster for y'all to track that down than for me to go try to dig it up myself

File: include/functor/rdx/truth_match.h (hunk 1 above)
Comment (afernez) [reply include/functor/rdx/truth_match.h:32]: Yeah these are the MC IDs for the $D^0$ sample (first two) and $D^*$ sample (last two) $DDX\mu$ decays

**Comment by yipengsun** [comment]
Some more debugging plots.

## `mDD`


test_d0
test_dst

## linear Dalitz variations, minus

There's a bunch of events w/ weight 1 indicating that they are NOT variated
wdal_lp_d0
wdal_lp_dst
